package com.blessingtree.service;

import com.blessingtree.dto.EmailDTO;
import com.blessingtree.model.Address;
import com.blessingtree.model.Sponsor;
import com.blessingtree.model.SponsorYear;

import java.util.*;

public class ParseBody {
    private static String[] values = {"*First Name:*", "*Last Name:*", "*Address:*", "*City:*", "*State:*",
            "*Zip:*", "*Email:*", "*Phone Number:*", "*Best Time To Call:*",
            "*Have you sponsored a child/children through The Blessing Tree Program\n" +
                    "before?:*",
            "*This year, each parent has indicated one wish / per child. How many\n" +
                    "children would you like to sponsor this year?:*",
            "*Do you have an age preference for the child that you would like to\n" +
                    "sponsor?:*",
            "*Do you have a preference on the gender of the child that you would like to\n" +
                    "sponsor?:*",
            "*How did you hear about St. Mary Magdalene’s Blessing Tree Program?:*",
            "*Would you be interested in becoming a volunteer of Magdalene House Social\n" +
                    "Services?:*"};
    public static void main(String[] args){
        EmailDTO emailDTO = getEmailDTO();
        Sponsor sponsor = new Sponsor();

        String[] body = emailDTO.getBody().split("\\*Blessing Tree Sponsor <https://st-mm.com/blessing-tree-sponsor-survey>\\*");
        String heads = body[1].trim();
        List<String> entityValues = new ArrayList<>();

        for(int i = 0; i < values.length - 1; i++){
            String out;

            if (i + 1 <= values.length - 1){
                out = heads.substring(heads.indexOf(values[i]) + values[i].length(), heads.indexOf(values[i + 1])).trim();
            }else{
                out = heads.substring(heads.indexOf(values[i]) + values[i].length(), heads.length()).trim();
            }

            if (out.isBlank() || out.isEmpty()){
                entityValues.add("");
            }else{
                entityValues.add(out.replace("\n", " "));
            }
        }

        sponsor.setFirstName(entityValues.get(0));
        sponsor.setLastName(entityValues.get(1));

        Address address = new Address();
        address.setStreet(entityValues.get(2));
        address.setCity(entityValues.get(3));
        address.setState(entityValues.get(4));
        address.setZip(entityValues.get(5));
        sponsor.setAddress(address);
        sponsor.setEmail(entityValues.get(6));
        sponsor.setPhone(entityValues.get(7));
        sponsor.setBestTimeToCall(entityValues.get(8));
        sponsor.setHasSponsoredPreviously(false); //9
//        SponsorYear sponsorYear = new SponsorYear();
//        sponsorYear.setNumberOfChildrenSponsored(Long.valueOf(entityValues.get(10)));
//        sponsorYear.setChildAgePreference(entityValues.get(11));
//        sponsorYear.setGenderPreference(entityValues.get(12));
//        sponsor.getSponsorYear().add(sponsorYear);
        sponsor.setHowDidYouHearAboutUs(entityValues.get(13));
        sponsor.setWantToVolunteer(false); //14


        System.out.println(sponsor);
    }

    private static EmailDTO getEmailDTO(){
        EmailDTO emailDTO = new EmailDTO();
        emailDTO.setBody("---------- Forwarded message ---------\n" +
                "From: 2022BT Program <2022mhbt@gmail.com>\n" +
                "Date: Mon, Nov 11, 2024 at 3:41 PM\n" +
                "Subject: Fwd: Online Form Submitted to Blessing Tree Sponsor\n" +
                "To: mhbtree@gmail.com <mhbtree@gmail.com>\n" +
                "\n" +
                "\n" +
                "\n" +
                "\n" +
                "---------- Forwarded message ---------\n" +
                "From: eCatholic [NO-REPLY] <noreply@ecatholicnotifications.com>\n" +
                "Date: Fri, Nov 1, 2024 at 10:26 AM\n" +
                "Subject: Online Form Submitted to Blessing Tree Sponsor\n" +
                "To: <2022mhbt@gmail.com>\n" +
                "\n" +
                "\n" +
                "*DO NOT REPLY TO THIS E-MAIL.* This e-mail was automatically generated by a\n" +
                "form on the *St. Mary Magdalene Catholic Community website* (powered by\n" +
                "eCatholic\n" +
                "<https://www.ecatholic.com/?referral=marketing#oid=1008_2_CMSemail>).\n" +
                "\n" +
                "\n" +
                "*Blessing Tree Sponsor <https://st-mm.com/blessing-tree-sponsor-survey>*\n" +
                "\n" +
                "*First Name:* Kerry\n" +
                "*Last Name:* Cowan\n" +
                "*Address:* 2111 Lost Maples Trail\n" +
                "*City:* Kingwood\n" +
                "*State:* TX\n" +
                "*Zip:* 77345\n" +
                "*Email:* kacowan10@gmail.com\n" +
                "*Phone Number:* 8322336868\n" +
                "*Best Time To Call:*\n" +
                "*Have you sponsored a child/children through The Blessing Tree Program\n" +
                "before?:* YES\n" +
                "*This year, each parent has indicated one wish / per child. How many\n" +
                "children would you like to sponsor this year?:* 3\n" +
                "*Do you have an age preference for the child that you would like to\n" +
                "sponsor?:*\n" +
                "*Do you have a preference on the gender of the child that you would like to\n" +
                "sponsor?:*\n" +
                "*How did you hear about St. Mary Magdalene’s Blessing Tree Program?:* I/my\n" +
                "family have participated in it before\n" +
                "*Would you be interested in becoming a volunteer of Magdalene House Social\n" +
                "Services?:*");

        return emailDTO;
    }


}
